version: "3.9"
services:
  postgres:
    container_name: pg-db
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - ./provision:/docker-entrypoint-initdb.d